### ISSUE TITLE
Cannot add charge points

### ISSUE THREAD

**Issue by sleepmaker** [kaohlive/com.newmotion.my#4]
I personally have 2 private charge points (Lolo Smart & Home Advanced), but neither one of them shows up after trying to add a device in my Homey.

**Comment by kaohlive** [comment]
Yes, sorry about that. Somehow the driver.js file got lost in the publish. I resubmitted 2.0.1 3 days ago that should fix this. But it is still pending approval :(

**Comment by kaohlive** [comment]
Still pending approval :(

**Comment by kaohlive** [comment]
Its finally approved and I just published it.
So can you check if your app was updated and try to add the chargepoints again.

If you would be so kind to provide feedback when you did, than I can close the issue or we can try to figure out what else could be a problem. I never tested the interface with more than 1 chargepoint, although its written to support it (but only with one chargecard right now)
